// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPE3pxVf9fu8aIpQQWpaep7DkR-yMHon8',
    appId: '1:387138014774:web:bfbb2829d38f13851bd297',
    messagingSenderId: '387138014774',
    projectId: 'ayantra',
    authDomain: 'ayantra.firebaseapp.com',
    storageBucket: 'ayantra.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPcnowh4264p-6EfRbP2LEc-vn9-baQAY',
    appId: '1:387138014774:android:c798c3b1af0fc5c51bd297',
    messagingSenderId: '387138014774',
    projectId: 'ayantra',
    storageBucket: 'ayantra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgW0GPudMCoMFAkMvyQP1TFPYfc3_9cqo',
    appId: '1:387138014774:ios:0742ca9b2755b3f01bd297',
    messagingSenderId: '387138014774',
    projectId: 'ayantra',
    storageBucket: 'ayantra.firebasestorage.app',
    iosBundleId: 'com.example.ayantrauser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgW0GPudMCoMFAkMvyQP1TFPYfc3_9cqo',
    appId: '1:387138014774:ios:0742ca9b2755b3f01bd297',
    messagingSenderId: '387138014774',
    projectId: 'ayantra',
    storageBucket: 'ayantra.firebasestorage.app',
    iosBundleId: 'com.example.ayantrauser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPE3pxVf9fu8aIpQQWpaep7DkR-yMHon8',
    appId: '1:387138014774:web:af82efa6ad6eed4a1bd297',
    messagingSenderId: '387138014774',
    projectId: 'ayantra',
    authDomain: 'ayantra.firebaseapp.com',
    storageBucket: 'ayantra.firebasestorage.app',
  );
}
